### ISSUE TITLE
一个fgm的问题。

### ISSUE THREAD

**Issue by orangetwo** [Decem-Y/sohu_text_matching_Rank2#1]
model = BertClassifierSingleModel(model_path)

    emb_name = 'bert.embeddings.'

    for name, param in model.named_parameters():

        if param.requires_grad and emb_name in name:

            print(name)

            print(param.shape)

结果为：
`bert.embeddings.word_embeddings.weight
torch.Size([21128, 768])
bert.embeddings.position_embeddings.weight
torch.Size([512, 768])
bert.embeddings.token_type_embeddings.weight
torch.Size([2, 768])
bert.embeddings.LayerNorm.weight
torch.Size([768])
bert.embeddings.LayerNorm.bias
`

fgm是不是不应该作用于 bert.embeddings.LayerNorm.weight、bert.embeddings.LayerNorm.bias 好一点呢？

**Comment by Decem-Y** [comment]
这里之前初赛使用的是bert.embeddings.，确实提升比较小，关于你提到的bert.embeddings.LayerNorm.weight、bert.embeddings.LayerNorm.bias由于比赛数据集过多，时间紧迫算力不足，后期未尝试fgm，你可以参考作者的[blog](https://fyubang.com/2019/10/15/adversarial-train/)作以对比尝试
